# .github/workflows/epub-multi-rend-11.yml
name: CI (Multiple Renditions)
on:
  workflow_dispatch:
  pull_request:
    paths: 
      - "wg-notes/multi-rend/**"
      - "common/**"
  push:
    branches: [main]
    paths: 
      - "wg-notes/multi-rend/**"
      - "common/**"
jobs:
  main:
    name: Publish EPUB Multiple-Rendition Publications 1.1 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: wg-notes/multi-rend/
          TOOLCHAIN: respec
          W3C_ECHIDNA_TOKEN: ${{ secrets.W3C_TR_TOKEN_MULTI_REND }}
          W3C_WG_DECISION_URL: https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2020-11-20-epub#resolution2
          W3C_BUILD_OVERRIDE: |
             shortName: epub-multi-rend-11
             specStatus: NOTE
