# .github/workflows/epub-multi-rend-11.yml
name: CI (EPUB TTS)
on:
  workflow_dispatch:
  pull_request:
    paths: 
      - "wg-notes/tts/**"
      - "common/**"
  push:
    branches: [main]
    paths: 
      - "wg-notes/tts/**"
      - "common/**"
jobs:
  main:
    name: Publish EPUB 3 Text-to-Speech Enhancements 1.0 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: wg-notes/tts/
          TOOLCHAIN: respec
          W3C_ECHIDNA_TOKEN: ${{ secrets.W3C_TR_TOKEN_TTS }}
          W3C_WG_DECISION_URL: https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2021-07-08-epub#resolution3
          W3C_BUILD_OVERRIDE: |
             shortName: epub-tts-10
             specStatus: NOTE
