# .github/workflows/epub-a11y-exemption-property.yml
name: CI (EPUB Accessibility Exemption Property)
on:
  workflow_dispatch:
  pull_request:
    paths: 
      - "wg-notes/a11y-exemption/**"
      - "common/**"
  push:
    branches: [main]
    paths: 
      - "wg-notes/a11y-exemption/**"
      - "common/**"
jobs:
  main:
    name: Publish EPUB Accessibility Exemption Property 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: wg-notes/a11y-exemption/
          TOOLCHAIN: respec
          W3C_ECHIDNA_TOKEN: ${{ secrets.W3C_TR_TOKEN_A11Y_EXEMPTION }}
          W3C_WG_DECISION_URL: https://lists.w3.org/Archives/Public/public-pm-wg/2023Oct/0028.html
          W3C_BUILD_OVERRIDE: |
             shortName: epub-a11y-exemption
             specStatus: NOTE
