# .github/workflows/epub-a11y-12.yml
name: CI (EPUB Accessibility)
on:
  pull_request:
    paths: 
      - "epub34/a11y/**"
      - "epub34/acknowledgements.html"
      - "common/**"
  push:
    branches: [main]
    paths: 
      - "epub34/a11y/**"
      - "epub34/acknowledgements.html"
      - "common/**"
jobs:
  main:
    name: Publish EPUB Accessibility 1.2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: epub34/a11y/
          TOOLCHAIN: respec
          W3C_ECHIDNA_TOKEN: ${{ secrets.W3C_TR_TOKEN_A11Y }}
          W3C_WG_DECISION_URL: https://www.w3.org/2025/03/13-pmwg-minutes.html#d175
          W3C_BUILD_OVERRIDE: |
             shortName: epub-a11y-12
             specStatus: WD
